### ISSUE TITLE
SendInvoice Pay XTR

### ISSUE THREAD

**Issue by panaoshuai** [raminsa/telegram-bot-api#1]
Hello, I am unable to make a payment using SendInvoice for XTR. Upon reviewing your code and comparing it with the official documentation, I noticed that you are forcing the use of ProviderToken and SuggestedTipAmounts. Could you please fix this? According to the Telegram documentation, ProviderToken is not required for XTR payments, or are you using a different method?

**Comment by raminsa** [comment]
The issue has been resolved, and you can now use the SendInvoice for XTR without any problems[ v0.7.5](https://github.com/raminsa/telegram-bot-api/releases/tag/v0.7.5). Please let us know if you encounter any further issues.
